#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019, 2020, 2021, 2022, 2023 Jack Consoli.  All rights reserved.
#
# NOT BROADCOM SUPPORTED
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may also obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
:mod:`report` - Creates a report in Excel Workbook format from a brcddb project

* Inputs:
    * -i=<Name of input file generated by capture.py or combine.py>
    * -o=<Name of output (report) file - report.xlsx>
    * -suppress<bool flag> suppress all output except final status code. Useful for batch processing
        Optional

* Outputs:
    * Excel Workbook

Version Control::

    +-----------+---------------+-----------------------------------------------------------------------------------+
    | Version   | Last Edit     | Description                                                                       |
    +===========+===============+===================================================================================+
    | 1.x.x     | 03 Jul 2019   | Experimental                                                                      |
    | 2.x.x     |               |                                                                                   |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.0     | 19 Jul 2020   | Initial Launch                                                                    |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.1     | 02 Sep 2020   | Added ability to customize the report                                             |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.2     | 31 Dec 2020   | Improved help messages.                                                           |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.3     | 09 Jan 2021   | Open log file.                                                                    |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.4     | 13 Feb 2021   | Added automatic .xlsx extension for output file and SFP file is not specified.    |
    |           |               | Added # -*- coding: utf-8 -*-                                                     |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.5     | 14 Aug 2021   | Added zone by target.                                                             |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.6     | 14 Nov 2021   | Improved user feedback messaging                                                  |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.7     | 31 Dec 2021   | Use brcddb.util.file.full_file_name()                                             |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.8     | 28 Apr 2022   | Removed custom pages add and remove.                                              |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.0.9     | 22 Jun 2022   | Added error message when the folder for the project file does not exist.          |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.1.0     | 01 Jan 2023   | Added shebang line. Added read of best practice tables.                           |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.1.1     | 21 Jan 2023   | Added input string to description so it's added to the report.                    |
    +-----------+---------------+-----------------------------------------------------------------------------------+
    | 3.1.2     | 11 Feb 2023   | Added zone groups, -g, options.                                                   |
    +-----------+---------------+-----------------------------------------------------------------------------------+
"""

__author__ = 'Jack Consoli'
__copyright__ = 'Copyright 2019, 2020, 2021, 2022, 2023 Jack Consoli'
__date__ = '11 Feb 2023'
__license__ = 'Apache License, Version 2.0'
__email__ = 'jack.consoli@broadcom.com'
__maintainer__ = 'Jack Consoli'
__status__ = 'Released'
__version__ = '3.1.2'

import argparse
import brcdapi.log as brcdapi_log
import brcdapi.file as brcdapi_file
import brcdapi.excel_util as excel_util
import brcdapi.gen_util as gen_util
import brcdapi.port as brcdapi_port
import brcddb.brcddb_project as brcddb_project
import brcddb.apps.report as brcddb_report
import brcddb.brcddb_common as brcddb_common
import brcddb.brcddb_bp as brcddb_bp
import brcddb.app_data.alert_tables as al
import brcddb.util.iocp as brcddb_iocp
import brcddb.util.obj_convert as brcddb_conv
import brcddb.brcddb_port as brcddb_port
import brcddb.util.search as brcddb_search

_DOC_STRING = False  # Should always be False. Prohibits any code execution. Only useful for building documentation
_DEBUG = False   # When True, use _DEBUG_xxx below instead of parameters passed from the command line.
_DEBUG_i = '_capture_2023_01_29_10_21_27/sw_2_217'
_DEBUG_o = 'test/test_report'
_DEBUG_bp = None  # 'bp'
_DEBUG_sup = False
_DEBUG_sfp = None  # 'sfp_rules_r10'
_DEBUG_iocp = None
_DEBUG_log = '_logs'
_DEBUG_nl = False
_DEBUG_c = None
_DEBUG_group = None  # 'test/group'

def _custom_report(proj_obj, options):
    """Modified as needed for custom reports. Intended for programmers customizing this script

    :param proj_obj: Project object
    :type proj_obj: brcddb.classes.project.ProjectObj
    :param options: As passed in via the shell
    :type options: str, None
    """

    return


def _filter_wwn(obj, filter_val, search):
    """Returns a list of login objects in obj"""
    return brcddb_conv.obj_extract(
        brcddb_search.match_test(
            brcddb_conv.obj_extract(obj, 'LoginObj'),
            dict(k='_obj_key', t=search, v=filter_val, i=True)),
        'PortObj')


def _filter_alias(obj, filter_val, search):
    """Returns a list of alias objects in obj"""
    return brcddb_conv.obj_extract(
        brcddb_search.match_test(
            brcddb_conv.obj_extract(obj, 'AliasObj'),
            dict(k='_obj_key', t=search, v=filter_val, i=True)),
        'PortObj'
    )


def _filter_switch_port(obj, filter_val, search):
    """Returns a list of port objects for the switch(es) and port(s) specified in filter_val"""
    switch_l, rl = list(), list()
    tl = filter_val.split(';') if isinstance(filter_val, str) else list()
    if len(tl) >= 2:
        for switch in tl[0].split(','):
            switch_l.extend([obj.r_switch_obj(switch)] if gen_util.is_wwn(switch)
                            else brcddb_project.switch_obj_for_user_name(obj, switch, match_type=search))
        port_l = brcdapi_port.port_range_to_list(tl[1])
        for switch_obj in switch_l:
            rl.extend([switch_obj.r_port_obj(p) for p in port_l if switch_obj.r_port_obj(p) is not None])
    else:
        brcdapi_log.exception('Invalid filter_val. Type: ' + str(type(filter_val)) + ', Val: ' + str(filter_val),
                              echo=True)

    return rl


def _filter_switch_port_name(obj, filter_val, search):
    """Returns a list of port objects for the switch(es) and port(s) specified in filter_val"""
    switch_l, rl = list(), list()
    tl = filter_val.split(';') if isinstance(filter_val, str) else list()
    if len(tl) >= 2:
        for switch in tl[0].split(','):
            switch_l.extend([obj.r_switch_obj(switch)] if gen_util.is_wwn(switch)
                            else brcddb_project.switch_obj_for_user_name(obj, switch))
        for switch_obj in switch_l:
            for name in tl[1].split(','):
                rl.extend(brcddb_port.port_objects_for_name(switch_obj, name, search=search))
    else:
        brcdapi_log.exception('Invalid filter_val. Type: ' + str(type(filter_val)) + ', Val: ' + str(filter_val),
                              echo=True)

    return rl


def _filter_zone(obj, filter_val, search):
    """Returns a list of alias objects in obj"""
    return brcddb_conv.obj_extract(
        brcddb_search.match_test(
            brcddb_conv.obj_extract(obj, 'ZoneObj'),
            dict(k='_obj_key', t=search, v=filter_val, i=True)),
        'PortObj'
    )


_group_filter_list = {'WWN': _filter_wwn,
                      'Alias': _filter_alias,
                      'switch;port': _filter_switch_port,
                      'switch;port_name': _filter_switch_port_name,
                      'Zone': _filter_zone}


def _groups(proj_obj, file):
    """Modified as needed for custom reports. Intended for programmers customizing this script

    :param proj_obj: Project object
    :type proj_obj: brcddb.classes.project.ProjectObj
    :param file: Name of group definition workbook
    :type file: str, None
    :return: Dictionary whose key is the group name and the value is a list of login objects
    :rtype: dict
    """
    ml, group_d = list(), dict()
    if file is None:
        return group_d

    # Read the workbook
    try:
        al = excel_util.read_workbook(file, dm=3, sheets='parameters')[0]['al']
        if len(al) < 2:
            ml.append('No Filters defined in ' + file)
    except (IndexError, KeyError):
        ml.append('"parameters" sheet not found in ' + file)
    except FileNotFoundError:
        ml.append('File not found: ' + file)
    except FileExistsError:
        ml.append('The path, folder, does not exist: ' + file)
    if len(ml) > 0:
        brcdapi_log.log(ml, echo=True)
        return group_d

    # Find the column headers
    col_d = excel_util.find_headers(al[0])
    for key in ('Group', 'Filter', 'Operand', 'Operator'):
        if key not in col_d:
            ml.append(key + ' missing in ' + file)
    if len(ml) > 0:
        brcdapi_log.log(ml, echo=True)
        return group_d

    # Figure out what's in each group
    row = 1
    for row_l in al[1:]:
        row += 1
        group, g_filter, operand, operator =\
            row_l[col_d['Group']], row_l[col_d['Filter']], row_l[col_d['Operand']], row_l[col_d['Operator']]
        if not isinstance(group, str) or len(group) == 0:
            continue
        if not isinstance(g_filter, str) or g_filter not in _group_filter_list:
            ml.append('Unknown Filter, ' + str(g_filter) + ', at row ' + str(row))
        group_l = group_d.get(group)
        if group_l is None:
            group_l = list()
            group_d.update({group: group_l})
        group_l.extend(_group_filter_list[g_filter](proj_obj, operand, operator))

    return group_d


def _get_input():
    """Parses the module load command line

    :return i: Input file name
    :rtype i: str
    :return o: Output file name
    :rtype o: str
    :return sfp: Name of SFP rules file
    :rtype sfp: str, None
    :return iocp: Name of folder containing IOCP files
    :rtype iocp: str, None
    :return c: Custom report parameters passed to _custom_report(). Typically not used.
    :rtype c: str, None
    """
    global _DEBUG, _DEBUG_i, _DEBUG_o, _DEBUG_bp, _DEBUG_sfp, _DEBUG_sup, _DEBUG_iocp, _DEBUG_log, _DEBUG_nl, _DEBUG_c
    global _DEBUG_group, __version__

    if _DEBUG:
        args_i, args_o, args_bp, args_sfp, args_group, args_sup, args_iocp, args_log, args_nl, args_c =\
            _DEBUG_i, _DEBUG_o, _DEBUG_bp, _DEBUG_sfp, _DEBUG_group, _DEBUG_sup, _DEBUG_iocp, _DEBUG_log, _DEBUG_nl, \
            _DEBUG_c
    else:
        parser = argparse.ArgumentParser(description='Create a general report in Excel.')
        buf = 'Required. Name of input file generated by capture.py, combine.py, or multi_capture.py. Extension '\
              '".json" is automatically added if no extension present.'
        parser.add_argument('-i', help=buf, required=True)
        parser.add_argument('-o', help='Required. Name of report file. ".xlsx" automatically appended.', required=True)
        buf = 'Optional. Name of the Excel Workbook with best practice rules. ".xlsx" is automatically appended.'
        parser.add_argument('-bp', help=buf, required=False)
        buf = 'Optional. Name of the Excel Workbook with SFP thresholds. This is the same file used as input to '\
              'applications.maps_config. This is useful for checking SFPs against the new recommended MAPS rules '\
              'before implementing them or filling in missing rules. ".xlsx" is automatically appended.'
        parser.add_argument('-sfp', help=buf, required=False)
        buf = 'Optional. Name of Excel file containing group definitions. When specified, creates a zone sheet for '\
              'each group. Although intended for storage enclosures, any group can be defined. See groups.xlsx for an '\
              'example.'
        parser.add_argument('-group', help=buf, required=False)
        buf = 'Optional. For FICON environments only. Name of folder with IOCP files. All files in this folder must '\
              'be IOCP files (build I/O configuration statements from HCD) and must begin with the CEC serial number'\
              ' followed by \'_\'. Leading 0s are not required. Example, for a CEC with serial number '\
              '12345: 12345_M90_iocp.txt'
        parser.add_argument('-iocp', help=buf, required=False)
        buf = 'Optional. Suppress all output to STD_IO except the exit code and argument parsing errors. Useful with '\
              'batch processing where only the exit status code is desired. Messages are still printed to the log file'\
              '. No operands.'
        parser.add_argument('-sup', help=buf, action='store_true', required=False)
        buf = '(Optional) Directory where log file is to be created. Default is to use the current directory. The ' \
              'log file name will always be "Log_xxxx" where xxxx is a time and date stamp.'
        parser.add_argument('-log', help=buf, required=False, )
        buf = '(Optional) No parameters. When set, a log file is not created. The default is to create a log file.'
        parser.add_argument('-nl', help=buf, action='store_true', required=False)
        parser.add_argument('-c', help='(Optional) Custom parameter to be used with _custom_report()', required=False)
        args = parser.parse_args()
        args_i, args_o, args_bp, args_sfp, args_group, args_sup, args_iocp, args_log, args_nl, args_c =\
            args.i, args.o, args.bp, args.sfp, args.group, args.sup, args.iocp, args.log, args.nl, args.c

    # Set up log file and debug
    if args_sup:
        brcdapi_log.set_suppress_all()
    if not args_nl:
        brcdapi_log.open_log(args_log)

    # User feedback
    ml = ['report.py:            ' + __version__,
          'In file, -i:          ' + args_i,
          'Out file, -o:         ' + args_o,
          'SFP rules file, -sfp: ' + str(args_sfp),
          'Best practice, -bp:   ' + str(args_bp),
          'Custom, -c:           ' + str(args_c)]
    if _DEBUG:
        ml.insert(0, 'WARNING!!! Debug is enabled')

    return brcdapi_file.full_file_name(args_i, '.json'), \
           brcdapi_file.full_file_name(args_o, '.xlsx'), \
           brcdapi_file.full_file_name(args_bp, '.xlsx'), \
           brcdapi_file.full_file_name(args_sfp, '.xlsx'), \
           brcdapi_file.full_file_name(args_group, '.xlsx'), \
           args_iocp, \
           args_c, \
           ml


def pseudo_main():
    """Basically the main(). Did it this way so it can easily be used as a standalone module or called from another.

    :return: Exit code. See exist codes in brcddb.brcddb_common
    :rtype: int
    """
    # Get and validate user input
    inf, outf, bp_rules, sfp_rules, group_file, iocp, custom_parms, ml = _get_input()
    brcdapi_log.log(ml, echo=True)

    # Get the project object
    try:
        proj_obj = brcddb_project.read_from(inf)
    except FileNotFoundError:
        brcdapi_log.log('Input file, ' + inf + ', not found', echo=True)
        return brcddb_common.EXIT_STATUS_ERROR
    except FileExistsError:
        brcdapi_log.log('Folder in ' + inf + ' does not exist', echo=True)
        return brcddb_common.EXIT_STATUS_ERROR
    if proj_obj is None:
        return brcddb_common.EXIT_STATUS_ERROR
    proj_obj.s_description('\n'.join(ml))

    # Perform all pre-processing (parse IOCPs, build references, ...)
    brcdapi_log.log('Building cross references', echo=True)
    brcddb_project.build_xref(proj_obj)
    brcddb_project.add_custom_search_terms(proj_obj)
    brcdapi_log.log('Performing mainframe checks', echo=True)
    for file in brcdapi_file.read_directory(iocp):
        brcddb_iocp.parse_iocp(proj_obj, iocp + '/' + file)
    brcddb_bp.best_practice(bp_rules, sfp_rules, al.AlertTable.alertTbl, proj_obj)

    # Generate the report
    brcddb_report.report(proj_obj, outf, _groups(proj_obj, group_file))
    _custom_report(proj_obj, custom_parms)
    return brcddb_common.EXIT_STATUS_ERROR if proj_obj.r_is_any_error() else brcddb_common.EXIT_STATUS_OK


##################################################################
#
#                    Main Entry Point
#
###################################################################

# Read in the project file from which the report is to be created and convert to a project object
# Create project

if _DOC_STRING:
    brcdapi_log.close_log('_DOC_STRING is True. No processing', echo=True)
    exit(0)

_ec = pseudo_main()
brcdapi_log.close_log(['', 'Processing Complete. Exit code: ' + str(_ec)], echo=True)
exit(_ec)
